version: '3'

services:
  app:
    image: car_demo:latest
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
      - XAUTHORITY=/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority
    network_mode: host